-- base_schema.sql

-- 1. Create 'analyses' table (Legacy/Basic)
create table if not exists analyses (
  id bigint generated by default as identity primary key,
  access_key text not null unique,
  channel_name text not null,
  email text not null,
  analysis_status text default 'queued', -- queued, processing, completed, failed
  report_generated_at timestamp with time zone,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Create 'user_reports' table (Main for Frontend/Premium)
create table if not exists user_reports (
  id bigint generated by default as identity primary key,
  user_id text, -- optional if linking to auth users
  access_key text not null unique,
  channel_name text,
  channel_handle text,
  email text,
  status text default 'pending', -- pending, processing, completed, failed
  progress_percentage integer default 0,
  current_phase text,
  retry_count integer default 0,
  report_data jsonb, -- Stores the full analysis result
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Enable Realtime for user_reports (Safe Idempotent Check)
do $$
begin
  if not exists (
    select 1 from pg_publication_tables 
    where pubname = 'supabase_realtime' 
    and schemaname = 'public' 
    and tablename = 'user_reports'
  ) then
    alter publication supabase_realtime add table user_reports;
  end if;
end $$;
