-- Views Training Data Collection Schema
-- Requires creator opt-in to collect data

-- Table to store creator data collection preferences
create table if not exists creator_data_settings (
  id bigint generated by default as identity primary key,
  user_id text not null unique,
  channel_id text,
  data_collection_opt_in boolean not null default false,
  consent_timestamp timestamp with time zone,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Table to store early metrics for ML training
create table if not exists views_training_data (
  id bigint generated by default as identity primary key,
  video_id text not null unique,
  channel_id text not null,
  user_id text not null,
  
  -- Early metrics (collected at intervals)
  views_1h integer,
  views_6h integer,
  views_24h integer,
  likes_24h integer,
  comments_24h integer,
  
  -- Final metrics (collected after maturation)
  final_views_7d integer,
  final_views_30d integer,
  
  -- Metadata features
  title_length integer,
  has_number_in_title boolean,
  upload_hour integer, -- 0-23
  upload_day_of_week integer, -- 0-6 (Monday=0)
  subscriber_count_at_upload integer,
  
  -- Timestamps
  video_published_at timestamp with time zone,
  metrics_1h_collected_at timestamp with time zone,
  metrics_6h_collected_at timestamp with time zone,
  metrics_24h_collected_at timestamp with time zone,
  metrics_7d_collected_at timestamp with time zone,
  metrics_30d_collected_at timestamp with time zone,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  -- Status
  collection_status text default 'pending', -- pending, collecting, complete, failed
  
  -- Foreign key reference
  constraint fk_user_id foreign key (user_id) references creator_data_settings(user_id) on delete cascade
);

-- Index for efficient queries by channel
create index if not exists idx_views_training_channel on views_training_data(channel_id);

-- Index for finding videos ready for next collection step
create index if not exists idx_views_training_status on views_training_data(collection_status);
