-- Enable the pgvector extension to work with embedding vectors
create extension if not exists vector;

-- Create a table to store video embeddings
create table if not exists video_embeddings (
  id bigint generated by default as identity primary key,
  video_id text not null unique,
  embedding vector(384), -- 384 dimensions for all-MiniLM-L6-v2
  model_version text not null default 'all-MiniLM-L6-v2',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create an index for faster similarity search (optional, but recommended)
create index on video_embeddings using ivfflat (embedding vector_cosine_ops)
with (lists = 100);
